import type { CSSProperties } from "react";

export const s = {
  card: (status: "pending" | "accepted" | "rejected"): CSSProperties => ({
    border: "1px solid " + (status === "accepted" ? "var(--ok)" : "var(--border)"),
    borderRadius: 10,
    background: "var(--bg-surface)",
    padding: 14,
    opacity: status === "rejected" ? 0.55 : 1,
  }),
  headerRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  } satisfies CSSProperties,
  titleCol: { display: "flex", flexDirection: "column", gap: 6, flex: 1, minWidth: 0 } satisfies CSSProperties,
  ruleRow: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  rule: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  metaRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  supportNote: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  snippet: {
    marginTop: 8,
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "8px 10px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  actions: { display: "flex", alignItems: "center", gap: 8, flexShrink: 0 } satisfies CSSProperties,
  editRow: { display: "flex", flexDirection: "column", gap: 8, marginTop: 10 } satisfies CSSProperties,
  editInput: {
    width: "100%",
    fontSize: 13,
    padding: "6px 8px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  editTextarea: {
    width: "100%",
    fontSize: 12,
    fontFamily: "var(--font-mono, monospace)",
    padding: "6px 8px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    minHeight: 60,
  } satisfies CSSProperties,
  editActions: { display: "flex", gap: 8 } satisfies CSSProperties,
  editedTag: { fontSize: 11, color: "var(--text-muted)", fontStyle: "italic" } satisfies CSSProperties,
} as const;
