import type { CSSProperties } from "react";

export const s = {
  card: (status: "pending" | "accepted" | "rejected"): CSSProperties => ({
    border: "1px solid " + (status === "accepted" ? "var(--ok)" : "var(--border)"),
    borderRadius: 10,
    background: "var(--bg-surface)",
    padding: 18,
  }),
  headerRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 20,
  } satisfies CSSProperties,
  titleCol: { display: "flex", flexDirection: "column", gap: 10, flex: 1, minWidth: 0 } satisfies CSSProperties,
  ruleRow: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  rule: {
    fontSize: 15,
    fontWeight: 500,
    fontStyle: "italic",
    color: "var(--text-primary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  evidenceRow: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" } satisfies CSSProperties,
  evidencePath: { color: "var(--text-muted)" } satisfies CSSProperties,
  githubLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    marginLeft: 8,
    color: "var(--accent)",
  } satisfies CSSProperties,
  supportNote: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  snippet: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "10px 12px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  confidenceRow: { display: "flex", alignItems: "center", gap: 10, marginTop: 2 } satisfies CSSProperties,
  confidenceLabel: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  confidenceBar: { width: 120, flexShrink: 0 } satisfies CSSProperties,
  confidencePct: {
    fontSize: 12,
    color: "var(--text-secondary)",
    fontVariantNumeric: "tabular-nums",
  } satisfies CSSProperties,
  actions: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    flexShrink: 0,
    width: 140,
  } satisfies CSSProperties,
  editRow: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  editInput: {
    width: "100%",
    fontSize: 13,
    padding: "6px 8px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  editTextarea: {
    width: "100%",
    fontSize: 12,
    fontFamily: "var(--font-mono, monospace)",
    padding: "6px 8px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    minHeight: 60,
  } satisfies CSSProperties,
  editActions: { display: "flex", gap: 8 } satisfies CSSProperties,
  editedTag: { fontSize: 11, color: "var(--text-muted)", fontStyle: "italic" } satisfies CSSProperties,
} as const;
